/** Named Pittsburgh hangouts OSM often under-labels. Coords are public landmark locations. */

export const CURATED_PLACES = [
  { name: "Carnegie Mellon University", neighborhood: "Oakland", lat: 40.4432, lng: -79.9436, category: "hangout", place_type: "urban_core", kind: "university" },
  { name: "University of Pittsburgh", neighborhood: "Oakland", lat: 40.4443, lng: -79.9608, category: "hangout", place_type: "urban_core", kind: "university" },
  { name: "Cathedral of Learning", neighborhood: "Oakland", lat: 40.4443, lng: -79.9532, category: "sights", place_type: "urban_core", kind: "landmark" },
  { name: "Schenley Park", neighborhood: "Oakland", lat: 40.4346, lng: -79.9426, category: "outdoors", place_type: "park", kind: "park" },
  { name: "Phipps Conservatory", neighborhood: "Oakland", lat: 40.439, lng: -79.948, category: "sights", place_type: "park", kind: "garden" },
  { name: "Carnegie Museum of Natural History", neighborhood: "Oakland", lat: 40.4436, lng: -79.95, category: "sights", place_type: "urban_core", kind: "museum" },
  { name: "Carnegie Museum of Art", neighborhood: "Oakland", lat: 40.4435, lng: -79.9489, category: "sights", place_type: "urban_core", kind: "museum" },
  { name: "The Original Hot Dog Shop", neighborhood: "Oakland", lat: 40.4419, lng: -79.957, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Fuel & Fuddle", neighborhood: "Oakland", lat: 40.4408, lng: -79.9575, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Hemingway's Cafe", neighborhood: "Oakland", lat: 40.4404, lng: -79.9582, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Peter's Pub", neighborhood: "Oakland", lat: 40.4411, lng: -79.9578, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Panera Bread (Craig St)", neighborhood: "Oakland", lat: 40.4448, lng: -79.9492, category: "food", place_type: "food", kind: "cafe" },
  { name: "Point State Park", neighborhood: "Downtown", lat: 40.4417, lng: -80.0128, category: "outdoors", place_type: "park", kind: "park" },
  { name: "Market Square", neighborhood: "Downtown", lat: 40.4406, lng: -80.002, category: "sights", place_type: "urban_core", kind: "plaza" },
  { name: "PPG Place", neighborhood: "Downtown", lat: 40.4397, lng: -80.0034, category: "sights", place_type: "urban_core", kind: "landmark" },
  { name: "Duquesne Incline", neighborhood: "Mount Washington", lat: 40.4392, lng: -80.018, category: "sights", place_type: "transit", kind: "incline" },
  { name: "Monongahela Incline", neighborhood: "Mount Washington", lat: 40.4322, lng: -80.0035, category: "sights", place_type: "transit", kind: "incline" },
  { name: "Mount Washington Overlook", neighborhood: "Mount Washington", lat: 40.4289, lng: -80.0106, category: "sights", place_type: "urban_core", kind: "viewpoint" },
  { name: "PNC Park", neighborhood: "North Shore", lat: 40.4469, lng: -80.0057, category: "recreation", place_type: "entertainment", kind: "stadium" },
  { name: "Acrisure Stadium", neighborhood: "North Shore", lat: 40.4468, lng: -80.0158, category: "recreation", place_type: "entertainment", kind: "stadium" },
  { name: "Andy Warhol Museum", neighborhood: "North Shore", lat: 40.4484, lng: -80.0025, category: "sights", place_type: "urban_core", kind: "museum" },
  { name: "National Aviary", neighborhood: "North Side", lat: 40.4533, lng: -80.01, category: "sights", place_type: "entertainment", kind: "attraction" },
  { name: "Children's Museum of Pittsburgh", neighborhood: "North Side", lat: 40.4526, lng: -80.0066, category: "sights", place_type: "entertainment", kind: "museum" },
  { name: "Randyland", neighborhood: "Mexican War Streets", lat: 40.4548, lng: -80.0118, category: "sights", place_type: "urban_core", kind: "attraction" },
  { name: "Mattress Factory", neighborhood: "Mexican War Streets", lat: 40.4572, lng: -80.0124, category: "sights", place_type: "urban_core", kind: "museum" },
  { name: "Heinz History Center", neighborhood: "Strip District", lat: 40.4465, lng: -79.9923, category: "sights", place_type: "urban_core", kind: "museum" },
  { name: "Strip District (Penn Ave)", neighborhood: "Strip District", lat: 40.4504, lng: -79.9836, category: "shopping", place_type: "shopping", kind: "marketplace" },
  { name: "Wholey's", neighborhood: "Strip District", lat: 40.4508, lng: -79.9848, category: "food", place_type: "shopping", kind: "supermarket" },
  { name: "Primanti Bros (Strip)", neighborhood: "Strip District", lat: 40.4512, lng: -79.9832, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Cinderlands Warehouse", neighborhood: "Strip District", lat: 40.4538, lng: -79.9805, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "SouthSide Works", neighborhood: "South Side", lat: 40.4284, lng: -79.965, category: "shopping", place_type: "shopping", kind: "mall" },
  { name: "East Carson Street", neighborhood: "South Side", lat: 40.4286, lng: -79.9755, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Hofbräuhaus Pittsburgh", neighborhood: "South Side", lat: 40.4289, lng: -79.9642, category: "night_life", place_type: "entertainment", kind: "biergarten" },
  { name: "Station Square", neighborhood: "South Shore", lat: 40.4325, lng: -80.0045, category: "shopping", place_type: "shopping", kind: "mall" },
  { name: "Walnut Street", neighborhood: "Shadyside", lat: 40.451, lng: -79.9335, category: "shopping", place_type: "shopping", kind: "street" },
  { name: "Pamela's Diner (Shadyside)", neighborhood: "Shadyside", lat: 40.4516, lng: -79.933, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Noodlehead", neighborhood: "Bloomfield", lat: 40.4618, lng: -79.9468, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Tessaro's", neighborhood: "Bloomfield", lat: 40.4612, lng: -79.9495, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Little Italy Days Strip (Liberty Ave)", neighborhood: "Bloomfield", lat: 40.4615, lng: -79.9478, category: "food", place_type: "food", kind: "street" },
  { name: "Murray Avenue", neighborhood: "Squirrel Hill", lat: 40.4385, lng: -79.9228, category: "food", place_type: "food", kind: "street" },
  { name: "Frick Park", neighborhood: "Point Breeze", lat: 40.434, lng: -79.9035, category: "outdoors", place_type: "park", kind: "park" },
  { name: "Highland Park", neighborhood: "Highland Park", lat: 40.4788, lng: -79.9165, category: "outdoors", place_type: "park", kind: "park" },
  { name: "Pittsburgh Zoo & Aquarium", neighborhood: "Highland Park", lat: 40.484, lng: -79.914, category: "sights", place_type: "entertainment", kind: "zoo" },
  { name: "East Liberty Presbyterian Church", neighborhood: "East Liberty", lat: 40.4612, lng: -79.9265, category: "sights", place_type: "urban_core", kind: "landmark" },
  { name: "Target (East Liberty)", neighborhood: "East Liberty", lat: 40.4618, lng: -79.9218, category: "shopping", place_type: "shopping", kind: "department_store" },
  { name: "Bakery Square", neighborhood: "East Liberty", lat: 40.4565, lng: -79.9155, category: "hangout", place_type: "urban_core", kind: "plaza" },
  { name: "Row House Cinema", neighborhood: "Lawrenceville", lat: 40.4658, lng: -79.9605, category: "night_life", place_type: "entertainment", kind: "cinema" },
  { name: "Spirit", neighborhood: "Lawrenceville", lat: 40.4662, lng: -79.9608, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Butler Street", neighborhood: "Lawrenceville", lat: 40.4645, lng: -79.9628, category: "night_life", place_type: "urban_core", kind: "street" },
  { name: "Allegheny Cemetery", neighborhood: "Lawrenceville", lat: 40.4725, lng: -79.953, category: "sights", place_type: "park", kind: "cemetery" },
  { name: "The Waterfront", neighborhood: "Homestead", lat: 40.4095, lng: -79.91, category: "shopping", place_type: "shopping", kind: "mall" },
  { name: "Kennywood", neighborhood: "West Mifflin", lat: 40.3868, lng: -79.8618, category: "recreation", place_type: "entertainment", kind: "theme_park" },
  { name: "Sandcastle Waterpark", neighborhood: "West Homestead", lat: 40.3965, lng: -79.9215, category: "recreation", place_type: "entertainment", kind: "theme_park" },
  { name: "Carrie Blast Furnaces", neighborhood: "Swissvale", lat: 40.4125, lng: -79.8855, category: "sights", place_type: "urban_core", kind: "historic" },
  { name: "Rivers Casino", neighborhood: "North Shore", lat: 40.4462, lng: -80.0208, category: "night_life", place_type: "entertainment", kind: "casino" },
  { name: "Stage AE", neighborhood: "North Shore", lat: 40.4465, lng: -80.0128, category: "night_life", place_type: "entertainment", kind: "music_venue" },
  { name: "Benedum Center", neighborhood: "Downtown", lat: 40.4426, lng: -79.997, category: "night_life", place_type: "entertainment", kind: "theatre" },
  { name: "Heinz Hall", neighborhood: "Downtown", lat: 40.4429, lng: -80.0015, category: "night_life", place_type: "entertainment", kind: "theatre" },
  { name: "Byham Theater", neighborhood: "Downtown", lat: 40.4438, lng: -80.0028, category: "night_life", place_type: "entertainment", kind: "theatre" },
  { name: "Agua at Palomino", neighborhood: "Downtown", lat: 40.4412, lng: -80.0025, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Giovanni's Pizza (Oakland)", neighborhood: "Oakland", lat: 40.4402, lng: -79.9572, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Stack'd Burgers", neighborhood: "Oakland", lat: 40.4415, lng: -79.9568, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Ali Baba Restaurant", neighborhood: "Oakland", lat: 40.4406, lng: -79.9588, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Chipotle (Forbes)", neighborhood: "Oakland", lat: 40.4418, lng: -79.9555, category: "food", place_type: "food", kind: "fast_food" },
  { name: "Giant Eagle Market District (Shadyside)", neighborhood: "Shadyside", lat: 40.4545, lng: -79.9338, category: "food", place_type: "shopping", kind: "supermarket" },
  { name: "Aldi (East Liberty)", neighborhood: "East Liberty", lat: 40.4598, lng: -79.9268, category: "food", place_type: "shopping", kind: "supermarket" },
  { name: "Trader Joe's (East Liberty)", neighborhood: "East Liberty", lat: 40.4605, lng: -79.9235, category: "food", place_type: "shopping", kind: "supermarket" },
  { name: "Whole Foods (East Liberty)", neighborhood: "East Liberty", lat: 40.4602, lng: -79.9222, category: "food", place_type: "shopping", kind: "supermarket" },
  { name: "Schenley Plaza", neighborhood: "Oakland", lat: 40.4422, lng: -79.9518, category: "hangout", place_type: "park", kind: "plaza" },
  { name: "Flagstaff Hill", neighborhood: "Oakland", lat: 40.4395, lng: -79.9488, category: "outdoors", place_type: "park", kind: "park" },
  { name: "Panther Hollow Lake", neighborhood: "Oakland", lat: 40.4362, lng: -79.9485, category: "outdoors", place_type: "park", kind: "park" },
  { name: "Three Rivers Heritage Trail", neighborhood: "Strip District", lat: 40.448, lng: -79.99, category: "outdoors", place_type: "park", kind: "trail" },
  { name: "Roberto Clemente Bridge", neighborhood: "Downtown", lat: 40.4455, lng: -80.0028, category: "sights", place_type: "urban_core", kind: "landmark" },
  { name: "Andy Warhol Bridge", neighborhood: "Downtown", lat: 40.4458, lng: -80.0005, category: "sights", place_type: "urban_core", kind: "landmark" },
  { name: "Rachel Carson Bridge", neighborhood: "Downtown", lat: 40.4462, lng: -79.9978, category: "sights", place_type: "urban_core", kind: "landmark" },
  { name: "Union Standard", neighborhood: "Downtown", lat: 40.4418, lng: -79.9985, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Condado Tacos (Lawrenceville)", neighborhood: "Lawrenceville", lat: 40.4652, lng: -79.9615, category: "food", place_type: "food", kind: "restaurant" },
  { name: "Round Corner Cantina", neighborhood: "Lawrenceville", lat: 40.4628, lng: -79.9648, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Kelly's Bar", neighborhood: "East Liberty", lat: 40.4615, lng: -79.9288, category: "night_life", place_type: "entertainment", kind: "bar" },
  { name: "Kelly-Strayhorn Theater", neighborhood: "East Liberty", lat: 40.4618, lng: -79.9255, category: "night_life", place_type: "entertainment", kind: "theatre" },
  { name: "Mr. Smalls Theatre", neighborhood: "Millvale", lat: 40.4795, lng: -79.9735, category: "night_life", place_type: "entertainment", kind: "music_venue" },
  { name: "Roxian Theatre", neighborhood: "McKees Rocks", lat: 40.4668, lng: -80.0655, category: "night_life", place_type: "entertainment", kind: "music_venue" },
  { name: "The Andy Warhol Museum cafe", neighborhood: "North Shore", lat: 40.4484, lng: -80.0025, category: "food", place_type: "food", kind: "cafe" },
  { name: "Sen. John Heinz History Center Smithsonian", neighborhood: "Strip District", lat: 40.4465, lng: -79.9923, category: "sights", place_type: "urban_core", kind: "museum" },
];
